name = "WunDeeDB"
uuid = "3b576da0-2f9f-4b64-bd33-cc2f6f73d57a"
authors = ["Alexander V. Mantzaris"]
version = "1.0.0-DEV"

[deps]
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
